# Site settings
title: 'Cassio Pimentel'
description: 'Desenvolvedor de Software'
url: 'http://cassiopimentel.github.io/'
baseurl: 'http://cassiopimentel.github.io/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'cassiopimentel'

author:
  name: 'Cassio Alves Pimentel'
  email: cassiowin98@yahoo.com.br
  twitter_username: 
  facebook_username:
  github_username:  cassiopimentel
  linkedin_username:  cassioalvespimentel

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: :year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
